
from enum import Enum


class PacketType(Enum):
    SEED = "SEED"
    DISCOVERY_REQUEST = "DREQ"
    DISCOVERY_RESPONSE = "DRES"
    PACKAGE_REQUEST = "PREQ"
    PACKAGE_RESPONSE = "PRES"
    DOWNLOAD_REQUEST = "DLRQ"
    DOWNLOAD_RESPONSE = "DLRS"
    DOWNLOAD_STATUS_REQUEST = "DSRQ"
    DOWNLOAD_STATUS_RESPONSE = "DSRS"
    EMPTY = "EMTY"
    FILE_CHECK_REQUEST = "FCHK"
    FILE_CHECK_RESPONSE = "FCKR"
    FILE_REQUEST = "FREQ"
    FILE_RESPONSE = "FRES"